language: ruby
cache: bundler
sudo: false
rvm: 2.4.0
install:
- bundle install
- bundle exec rake prebuild:install
script:
- bundle exec rake build:prod
- bundle exec rake postbuild:test
addons:
  ssh_known_hosts: ssh-sudweb.alwaysdata.net
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
after_deploy:
- ssh-agent -k
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet --exclude '.ssh' $TRAVIS_BUILD_DIR/_site/blog/ sudweb_blog@ssh-sudweb.alwaysdata.net:/home/sudweb/www/blog/
  on:
    branch: green
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- openssl aes-256-cbc -K $encrypted_7d3776e481e4_key -iv $encrypted_7d3776e481e4_iv
  -in deploy_rsa.enc -out deploy_rsa -d
